name = "TFAR Radio Settings Save & Restore";
author = "Darojax";
actionName = "GitHub";
action = "https://github.com/Darojax/TFAR-Radio-Settings-Save-and-Restore";
description = "Save and manually restore personal TFAR radio settings across Arma sessions.";
tooltip = "TFAR Radio Settings Save & Restore";
tooltipOwned = "TFAR Radio Settings Save & Restore";
overview = "Named personal TFAR radio settings with deliberate manual saving and restoration.";
overviewText = "TFAR Radio Settings Save & Restore";
