name = "TFAR Radio Settings Save & Restore"
prefix = "tfarp"
mainprefix = "z"

[version]
major = 0
minor = 2
patch = 1
git_hash = 0

[files]
include = [
    "ARTWORK_LICENSE.md",
    "LICENSE",
    "assets/*_ca.paa",
    "mod.cpp",
    "README.md",
]

[properties]
author = "Darojax"
url = "https://github.com/Darojax/TFAR-Radio-Settings-Save-and-Restore"
