name = "TFAR Persistence"
prefix = "tfarp"
mainprefix = "z"

[version]
major = 0
minor = 1
patch = 0
git_hash = 0

[files]
include = [
    "LICENSE",
    "mod.cpp",
    "README.md",
]

[properties]
author = "Darojax"
url = "https://github.com/Darojax/TFAR-Persistence"
